### ISSUE TITLE
Katex support

### ISSUE THREAD

**Issue by nathom** [schnerring/hugo-theme-gruvbox#156]
Hey, great work on the theme! I plan on using a lot of math equations so I was wondering whether you could add LaTeX rendering support. I could only get it working by editing the theme itself, but if there is a way without editing the theme directly, please let me know.

**Comment by schnerring** [comment]
Would you wanna use [KaTeX](https://www.npmjs.com/package/katex)?

**Comment by nathom** [comment]
Just opened a PR. LMK if it's acceptable. I don't have a lot of experience with Hugo.

**Comment by schnerring** [comment]
[The theme already offers extensibility](https://github.com/schnerring/hugo-theme-gruvbox#extensibility), so no change to the theme is required. Just add the code from your PR to a file named `layouts/partials/head/head_end.html`.

If you want to manage `katex` with npm, add the following to `package.hugo.json`:

```json
  "dependencies": {
    "katex": "^0.16.8"
  }
```

Run `hugo mod npm pack` to sync `package.hugo.json` to `package.json`. Then run `npm install`. After, mount the `node_modules/katex` folder via `config/_default/module.toml`:

```toml
[[mounts]]
  source = "node_modules/katex"
  target = "assets/katex"
```

Finally add the following `layouts/partials/head/head_end.html`:

```html
{{ if .Params.katex }}
  {{ $katexCSS := resources.Get "katex/dist/katex.min.css" }}
  <link
    rel="stylesheet"
    href="{{ $katexCSS }}"
    {{ if hugo.IsProduction }}
      integrity="{{ $katexCSS.Data.Integrity }}"
    {{ end }}
    crossorigin="anonymous"
  />

  {{ $katexJS := resources.Get "katex/dist/katex.min.js" }}
  <script
    defer
    src="{{ $katexJS.RelPermalink }}"
    {{ if hugo.IsProduction }}
      integrity="{{ $katexJS.Data.Integrity }}"
    {{ end }}
    crossorigin="anonymous"
  ></script>

  {{ $autoRender := resources.Get "katex/dist/contrib/auto-render.min.js" }}
  <script
    defer
    src="{{ $autoRender.RelPermalink }}"
    {{ if hugo.IsProduction }}
      integrity="{{ $autoRender.Data.Integrity }}"
    {{ end }}
    crossorigin="anonymous"
    onload="renderMathInElement(document.body);"
  ></script>
{{ end }}
```

The only thing left is enabling katex in the front matter of your content like this:

```markdown
---
title: "Hello World"
description: "The first post of this blog"
date: 2021-03-14T15:00:21+01:00
draft: false
katex: true
---

I'm a .NET developer by trade, so let's say hello in C#!
```
