### ISSUE TITLE
Theme Installation Issue

### ISSUE THREAD

**Issue by feynmans-socks** [schnerring/hugo-theme-gruvbox#158]
**Output from `hugo server`**:
Start building sites …
hugo v0.116.1-3e1ea030a5897addaf9d113d0826709fe07f77c0+extended windows/amd64 BuildDate=2023-08-01T07:24:54Z VendorInfo=gohugoio

WARN  found no layout file for "html" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN  found no layout file for "html" for kind "home": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.

-------------------+-----
  Pages            |  3
  Paginator pages  |  0
  Non-page files   |  0
  Static files     |  0
  Processed images |  0
  Aliases          |  0
  Sitemaps         |  1
  Cleaned          |  0

Built in 5 ms
Environment: "development"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)

**Output on localhost**:
![image](https://github.com/schnerring/hugo-theme-gruvbox/assets/61772258/7b4d520e-89c6-4637-813d-e2eba1427c0e)

**OS**: Windows

[**Relevant Link**](https://gohugo.io/templates/lookup-order/)

**Comment by schnerring** [comment]
What are the installation steps you performed? Do you have a publicly shared repo that reproduces the issue?

**Comment by TheGoldenFang** [comment]
I followed the following steps and was able to reproduce the same issue (Page not found).

- `hugo new site site-name`
- `cd site-name`
- `hugo mod init site-name`
- Copied stuff into TOML config file (hugo.toml)
- `hugo mod get`

```
go: no module dependencies to download
hugo: downloading modules …
go: downloading github.com/schnerring/hugo-mod-json-resume v0.0.0-20230730034443-b31a3e85d57e
go: added github.com/schnerring/hugo-mod-json-resume v0.0.0-20230730034443-b31a3e85d57e
hugo: collected modules in 18032 ms
```
- `hugo mod npm pack`
- `npm install`

```

added 137 packages, and audited 138 packages in 1m

42 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
- `hugo server`

```
Watching for changes in S:\site-name\{archetypes,assets,content,data,layouts,node_modules,package.hugo.json,package.json,static}
Watching for config changes in S:\site-name\hugo.toml, S:\site-name\go.mod
Start building sites …
hugo v0.116.1-3e1ea030a5897addaf9d113d0826709fe07f77c0+extended windows/amd64 BuildDate=2023-08-01T07:24:54Z VendorInfo=gohugoio

WARN  found no layout file for "html" for kind "home": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN  found no layout file for "html" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.

                   | EN
-------------------+-----
  Pages            |  3
  Paginator pages  |  0
  Non-page files   |  0
  Static files     |  0
  Processed images |  0
  Aliases          |  0
  Sitemaps         |  1
  Cleaned          |  0

Built in 12 ms
Environment: "development"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop
```

Opened the site in a browser to receive the same "Page Not Found" message.

**Note**: the directories in the site-name are empty, showing the tree of the site-name directory

```
As you can notice all the folders are empty except node modules.
├───archetypes
├───assets
├───content
├───data
├───layouts
├───node_modules
│   ├───.bin
│   ├───@isaacs
│   │   └───cliui
....... Loads of node module packages .....
├───resources
│   └───_gen
│       ├───assets
│       └───images
├───static
└───themes
```

**Comment by schnerring** [comment]
Thanks for your very detailed steps!

```text
Copied stuff into TOML config file (hugo.toml)
```

You found an issue in the README. Try adding the following below `[module]` in yourhugo.toml file:

```toml
  [[module.imports]]
    path = "github.com/schnerring/hugo-theme-gruvbox"
```

Then run:

```bash
hugo mod get
hugo mod npm pack
npm install
hugo server
```

Sorry about that, the quickstart sample config doesn't include the actual theme module. 😅

**Comment by feynmans-socks** [comment]
> What are the installation steps you performed? Do you have a publicly shared repo that reproduces the issue?

I had completely forgotten! Thank you @TheGoldenFang!

Getting another problem though:

```
- hugo new site example
- cd example
- hugo mod init example
```
Added the fixed stuff into hugo.toml
```
- hugo mod get
```
```
go: no module dependencies to download
hugo: downloading modules …
go: downloading github.com/schnerring/hugo-theme-gruvbox v0.0.0-20230805223643-fe0ef9691a3d
go: added github.com/schnerring/hugo-theme-gruvbox v0.0.0-20230805223643-fe0ef9691a3d
hugo: collected modules in 4055 ms
```
```
- hugo mod npm pack
```
```
added 527 packages, and audited 528 packages in 51s

187 packages are looking for funding
  run `npm fund` for details
```
```
- npm install
- hugo server
```
```
Watching for changes in C:\Users\...\example\{archetypes,assets,content,data,layouts,node_modules,package.hugo.json,package.json,static}
Watching for config changes in C:\Users\...\example\hugo.toml, C:\Users\...\example\portfolio\go.mod
Start building sites …
hugo v0.116.1-3e1ea030a5897addaf9d113d0826709fe07f77c0+extended windows/amd64 BuildDate=2023-08-01T07:24:54Z VendorInfo=gohugoio

ERROR POSTCSS: failed to transform "." (application/octet-stream): 'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
ERROR POSTCSS: failed to transform "css/non-critical.css" (text/css): 'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
Built in 198 ms
Error: error building site: render: failed to render pages: render of "home" failed: "C:\Users\...\AppData\Local\hugo_cache\modules\filecache\modules\pkg\mod\github.com\schnerring\hugo-theme-gruvbox@v0.0.0-20230805223643-fe0ef9691a3d\layouts\_default\baseof.html:6:5": execute of template failed: template: index.html:6:5: executing "index.html" at <partial "head/head.html" .>: error calling partial: "C:\Users\...\AppData\Local\hugo_cache\modules\filecache\modules\pkg\mod\github.com\schnerring\hugo-theme-gruvbox@v0.0.0-20230805223643-fe0ef9691a3d\layouts\partials\head\head.html:12:5": execute of template failed: template: partials/head/head.html:12:5: executing "partials/head/head.html" at <partial "head/stylesheets.html" .>: error calling partial: "C:\Users\...\AppData\Local\hugo_cache\modules\filecache\modules\pkg\mod\github.com\schnerring\hugo-theme-gruvbox@v0.0.0-20230805223643-fe0ef9691a3d\layouts\partials\head\stylesheets.html:18:14": execute of template failed: template: partials/head/stylesheets.html:18:14: executing "partials/head/stylesheets.html" at <$critical.Content>: error calling Content: POSTCSS: failed to transform "." (application/octet-stream): 'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```
I get the same error after cloning the repository,  cd-ing into it, and running `hugo server`

**Comment by schnerring** [comment]
Can you move your repo to a folder path that doesn't contain spaces?

Related:

- https://github.com/gohugoio/hugo/issues/7333
- https://discourse.gohugo.io/t/postcss-does-not-work-in-directories-with-spaces/39101/5

**Comment by feynmans-socks** [comment]
It worked! Thank you!

My user on Windows has a space in it. Unfortunately, the module info was stored locally on the user, so I kept getting the error regardless of the location of my repo. I ended up having to create an entirely new user.
