### ISSUE TITLE
GETTING RID OF THE richard hendriks details

### ISSUE THREAD

**Issue by gitrospective** [schnerring/hugo-theme-gruvbox#202]
I am unable to get rid of the descriptions regarding richard hendriks

**Comment by schnerring** [comment]
This is described in the README: [Remove the Sidebar](https://github.com/schnerring/hugo-theme-gruvbox#remove-the-sidebar)

**Comment by gitrospective** [comment]
yeah I did that as instructed, but it doesn;t remove the sidebar

**Comment by davegallant** [comment]
It works if you place it in `data/json_resume/en.json`. 

See https://github.com/schnerring/schnerring.github.io/tree/de5dcb7ffcc141e036179c2aefb641806acdfea6/data/json_resume
