### ISSUE TITLE
Hugo Version `v0.120.1+extended` requires a valid e-mail address when RSS is enabled

### ISSUE THREAD

**Issue by rklasen** [schnerring/hugo-theme-gruvbox#215]
Hi, thanks for this awesome theme, I am planning to use it for my site as well. I couldn't get the installation working with the readme, because this error happend:

```
ERROR render of "term" failed: template: _internal/_default/rss.xml:3:9: executing "_internal/_default/rss.xml" at <site>: can't evaluate field email in type string
ERROR render of "taxonomy" failed: template: _internal/_default/rss.xml:3:9: executing "_internal/_default/rss.xml" at <site>: can't evaluate field email in type string
Built in 1424 ms
Error: error building site: render: failed to render pages: render of "section" failed: template: _internal/_default/rss.xml:3:9: executing "_internal/_default/rss.xml" at <site>: can't evaluate field email in type string
```

To test a known working example site, I've cloned your [personal website](https://github.com/schnerring/schnerring.github.io) (thanks for making this possible, it's invaluable to see how the config is properly done). But it happens on your site too, which means the issues seems to appear somewhere between the hugo version you're using and `hugo v0.120.1+extended`.

Adding this to the `config/_default/config.toml` solves the issue, but obviously this disables RSS:

```
[outputs]
  home = ['html']
  section = ['html']
  taxonomy = ['html']
  term = ['html']
```

**Comment by schnerring** [comment]
I'm not sure if this is a Hugo bug or breaking change.

Looking at [these comments](https://github.com/gohugoio/hugo/commit/d4016dd5cd57a27f19a5472c6031d156066860b7#comments), I'd assume this is a bug.

Have you had a chance to test this with newer Hugo versions?
