### ISSUE TITLE
Unable to install the theme | hugo server failed to render pages

### ISSUE THREAD

**Issue by h-rajpal** [schnerring/hugo-theme-gruvbox#286]
Hi,

I have been trying to install the template for a personal website. The standalone theme works fine, however when I try to install it as a module for a site, hugo server is unable to build the site as it fails to render. Maybe I am doing something very obviously wrong. But I have tried to follow the installation instructions to the letter and some variations. The issue persists. 
I am using the following relevant package versions,

hugo v0.129.0+extended darwin/arm64 BuildDate=2024-07-17T13:29:16Z VendorInfo=brew
go version go1.22.5 darwin/arm64
git version 2.40.1

If there are any other suggestions for installing the theme other than as a module, I would appreciate them.
I thought it might have been a version mismatch. I tried the hugo v0.128.0+extended, and I still got the same error.
Attaching the image of the error log here,

![image](https://github.com/user-attachments/assets/1a5be5aa-b1b3-4837-a9a7-e2f6736b2f1b)

**Comment by julianaflima** [comment]
I'm having the same problem. I've tested with other themes and it works but this isn't working.

**Comment by C-rrente** [comment]
Seems like the theme is out of date

**Comment by mpcabete** [comment]
I am having the same issue

**Comment by schnerring** [comment]
It's probably time to overhaul the README. Maybe the instructions are outdated.

**Comment by mpcabete** [comment]
Can you point me in the direction of making it work as a theme in the meantime?

**Comment by schnerring** [comment]
I'm using it as theme on my own website. Here's the repo of my website: https://github.com/schnerring/schnerring.github.io

**Comment by mpcabete** [comment]
I have narrowed down this error to the missing data/json_resume/en.json file in a new installation, maybe add this step into the README.md

**Comment by julianaflima** [comment]
@mpcabete do you know how to fix this?

**Comment by mpcabete** [comment]
@julianaflima i fixed it by adding the data/json_resume/en.json to my project, otherwise hugo cannot find it and throws an error

**Comment by schnerring** [comment]
The theme / json resume module includes a default data/json_resume/en.json that you can import via Hugo module mount. Something seems to be broken there.

**Comment by schnerring** [comment]
I updated the theme's module config and README sample, which should fix the issue. The module config is a bit convoluted, but currently I don't see any way to simplify it. See related issue: https://github.com/schnerring/hugo-theme-gruvbox/issues/16
