### ISSUE TITLE
Any way to remove the sidebar with the profile and bio?

### ISSUE THREAD

**Issue by DarrienG** [schnerring/hugo-theme-gruvbox#31]
I'd love to be able to use this as just a blog without my big head, socials, and bio on the side. Any way to remove it via the config? I can tear up the layout manually on my own locally, but I feel like there should be a better way.

**Comment by schnerring** [comment]
Sorry for the late response! I tested removing the sidebar by deleting the resume data in `data/en.json` like this:

```json
{
  "$schema": "https://raw.githubusercontent.com/jsonresume/resume-schema/v1.0.0/schema.json",
  "basics": {},
  "work": [],
  "education": [],
  "skills": [],
  "languages": [],
  "projects": [],
  "meta": {
    "canonical": "https://raw.githubusercontent.com/jsonresume/resume-schema/master/resume.json",
    "version": "v1.0.0",
    "lastModified": "2017-12-24T15:53:00"
  }
}
```

I'll add this to the README!
