### ISSUE TITLE
The download instructions are very unclear. 

### ISSUE THREAD

**Issue by frehburg** [schnerring/hugo-theme-gruvbox#32]
After these two steps:

Add the following to the config.toml file:
...

Install the theme:

hugo mod get

It says: 
WARN 2022/08/17 19:58:12 module "https://github.com/schnerring/hugo-mod-json-resume" not found; either add it as a Hugo Module or store it in "C:\\Hugo\\example.com\\themes".: module does not exist

**Comment by schnerring** [comment]
Just tested it, everything works fine.

Did you install Go? Are you using `hugo-extended`?

**Comment by frehburg** [comment]
Okay you were right. It didn't work because I didn't have Go installed. I
downloaded it, followed all the steps again and ran into another issue.

I created a new file in content. And then hosted the server with 'hugo
server' to see if it worked. But i got this error:

WARN 2022/08/17 23:20:39 found no layout file for "HTML" for kind "home":
You should create a template file which matches Hugo Layouts Lookup Rules
for this combination.

**Comment by schnerring** [comment]
Are you using `hugo` or `hugo-extended`?

**Comment by schnerring** [comment]
What steps have you taken to troubleshoot the issue? From your error message #33 :

> this feature is not available in your current Hugo version, see [https://goo.gl/YMrWcn](https://goo.gl/YMrWcn) for more information

Have you read the FAQ the error message links to?

**Comment by frehburg** [comment]
I am using hugo. Haven't looked into that one yet no.

**Comment by frehburg** [comment]
I upgraded to the extened hugo version and restarted your instructions from the beginning. But now when i run hugo server i get this error again:

WARN 2022/08/19 19:37:03 found no layout file for "HTML" for kind "home": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.

**Comment by schnerring** [comment]
Closing this as this is a user issue.

If you have a recommendation how to improve the installation docs, please let me know.
