### ISSUE TITLE
setting defaultTheme has no effect

### ISSUE THREAD

**Issue by mikefarmer01** [schnerring/hugo-theme-gruvbox#34]
Setting `params.defaultTheme` in ./config/_default/config.toml has no effect.
No matter whether set to "dark" or "light", the theme is always dark.

On the other hand, setting `params.themeColor` and `params.themeContrast` have the desired effects.

**Comment by schnerring** [comment]
Theme selection is a bit convoluted, I probably should add some explanations somewhere.

When the site initially loads, it will set `theme` attribute of the `html` properly:

https://github.com/schnerring/hugo-theme-gruvbox/blob/dbf1af452041c500e276dd6589963b081769c849/layouts/_default/baseof.html#L2-L5

Inside `dark-mode.js` this behavior is overriden by the following logic:

https://github.com/schnerring/hugo-theme-gruvbox/blob/dbf1af452041c500e276dd6589963b081769c849/assets/js/dark-mode.js#L1-L31

1. Check whether a preferred theme is stored inside local storage. This will always have a value after the page loaded for the first time (`Initial Load`). So if you debugged the page and set `defaultTheme` after, you'll have to delete cookies/site data.
2. Also, if the browser supports it, the OS theme-preference is checked which overrides `defaultTheme`. If you want to test this, disable JavaScript.
3. If neither (1) and (2) (`// Undefined`) are true, the `defaultTheme` will be displayed.

**Comment by mikefarmer01** [comment]
Understood.  
So in my case, it's because the brower's default theme.

Thanks for the detailed explanation.
Where should it be documented?

**Comment by jonnjonnjo** [comment]
I'm sorry, I'm a little bit confused. If I want to choose a color theme for the first time, should I add this code
``` 
 <html 
   lang="{{ .Site.Language.Lang | default "en" }}" 
   theme="{{ .Param "defaultTheme" | default "light" }}" 
 > 
``` 

to the ```layouts/_default/baseof.html``` ? But, the ```_default/baseof.html``` itself doesn't exist in my project. 

Does that means that I have to create the file and add the attribute ?
